main: poltixe.spigot.amongus.App
name: AmongUs
version: 0.1
api-version: 1.15
depend: [MinigameQueue]

commands:
    callmeeting:
      description: Calls an emergency meeting
      usage: /callmeeting
      permission: amongus.callmeeting
    vote:
      description: Vote for a player
      usage: /vote [playername]
      permission: amongus.vote